name: sample4
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  latlong2: ^0.8.2
  flutter_polyline_points: ^1.0.0
  location: ^4.3.0
  url_launcher: ^6.1.5
  webview_flutter: ^2.3.0
  firebase_auth: ^4.4.3
  firebase_core: ^2.10.0
  cloud_firestore: ^4.4.5
  firebase_database: ^10.4.0

  android_intent: ^2.0.0
  maps_launcher: ^2.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/
   
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
